# Stable (90 %)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app-stable
spec:
  replicas: 9
  # …same template as above with image tag "stable"
---
# Canary (10 %)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app-canary
spec:
  replicas: 1
  # …template uses image tag "${{ github.sha }}"

