apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app-stable
spec:
  replicas: 9
  selector:
    matchLabels:
      app: my-k8s-app
      version: stable
  template:
    metadata:
      labels:
        app: my-k8s-app
        version: stable
    spec:
      containers:
      - name: my-k8s-app-container
        image: kunj22/my-k8s-app:stable
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-k8s-app
      version: canary
  template:
    metadata:
      labels:
        app: my-k8s-app
        version: canary
    spec:
      containers:
      - name: my-k8s-app-container
        image: kunj22/my-k8s-app:canary
        ports:
        - containerPort: 80

