name: CI/CD to Kubernetes

on:
  push:
    branches: [main]

env:
  IMAGE: ${{ secrets.REGISTRY_HOST }}/my-k8s-app:${{ github.sha }}

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # ---------- Build & push ----------
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_HOST }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build & Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE }}

    # ---------- Deploy ----------
    - name: Set up Kubeconfig
      uses: azure/setup-kubectl@v3
      with:
        version: v1.30.0

    - name: Decode & save kubeconfig
      run: |
        echo "${KUBE_CONFIG_DATA}" | base64 -d > $HOME/.kube/config
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_B64 }}

    - name: Deploy to cluster
      run: |
        kubectl apply -f k8s/deployment.yaml --prune -l app=my-k8s-app
        kubectl apply -f k8s/service.yaml
      env:
        IMAGE: ${{ env.IMAGE }}

    - name: Verify rollout
      run: kubectl rollout status deployment/my-k8s-app

